name: fixit_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  flutter_bloc: null
  flutter_svg: ^2.0.17
  dio: null
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.8.0
  provider: null
  flutter_localization: ^0.3.1
  intl: ^0.19.0
  intl_utils: ^2.8.10
  supabase_flutter: ^2.8.4
  awesome_snackbar_content: ^0.1.5
  google_sign_in: ^6.3.0
  rive: ^0.13.20
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/animated-icons.riv

  # example:
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app.png"
  adaptive_icon_background: "assets/images/icon_app.png"
  adaptive_icon_foreground: "assets/images/icon_app.png"
  min_sdk_android: 23
flutter_intl:
  enabled: true
