const supabaseUrl = 'https://njastfiadyobibetjbql.supabase.co';
const supabaseKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYXN0ZmlhZHlvYmliZXRqYnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTEyNTMsImV4cCI6MjA1NzcyNzI1M30.N0TWNJ2fwrBba9WRJ-RS5E3o0wIY1DqXXgWm1FNV8mw';
